spring.application.name=Student.Management
spring.datasource.url=jdbc:mysql://localhost:3306/StudentManagement
spring.datasource.username=root
spring.datasource.password=A1b@2cD3e#4Fg5H
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatisn???
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath*:/mapper/*.xml
logging.level.org.mybatis=DEBUG
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
